//mod day01;
//mod day02;
//mod day03;
//mod day04;
//mod day05;
//mod day06;
//mod day07;
//mod day08;
//mod day09;
//mod day10;
//mod day11;
//mod day12;
//mod day13;
//mod day14;
//mod day15;
//mod day16;
//mod day17;
mod day18;
mod util;

fn main() {
  //  day01::compute(&util::file_lines("inputs/day01.txt"));
  //  day02::compute(&util::file_lines("inputs/day02.txt"));
  //  day03::compute(&util::file_lines("inputs/day03.txt"));
  //  day04::compute(&util::file_lines("inputs/day04.txt"));
  //  day05::compute(&util::file_lines("inputs/day05.txt"));
  //  day06::compute(&util::file_lines("inputs/day06.txt"));
  //  day07::compute(&util::file_lines("inputs/day07.txt"));
  //  day08::compute(&util::file_lines("inputs/day08.txt"));
  //  day09::compute(&util::file_lines("inputs/day09.txt"));
  //  day10::compute(&util::file_lines("inputs/day10.txt"));
  //  day11::compute();
  //  day12::compute(&util::file_lines("inputs/day12.txt"));
  //  day13::compute(&util::file_lines("inputs/day13.txt"));
  //  day14::compute();
  //  day15::compute(&util::file_lines("inputs/day15.txt"));
  //  day16::compute(&util::file_string("inputs/day16.txt"));
  //  day17::compute(&util::file_lines("inputs/day17.txt"));
  day18::compute(&util::file_lines("inputs/day18.txt"));
}
